--
-- PostgreSQL database dump
--

\restrict Hr2NXki0nOLDCZxAzfX5nF9YgSW2vVm3VL8gZw30mOcI0OWoVCQsRSkwctCeObc

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: reservables; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reservables (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    type character varying(100) NOT NULL,
    isactive boolean NOT NULL
);


ALTER TABLE public.reservables OWNER TO postgres;

--
-- Name: reservables_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.reservables_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.reservables_id_seq OWNER TO postgres;

--
-- Name: reservables_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.reservables_id_seq OWNED BY public.reservables.id;


--
-- Name: reservables_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reservables ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservables_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reservations (
    id bigint NOT NULL,
    reservable_id bigint CONSTRAINT reservations_use_id_not_null NOT NULL,
    user_id character varying(100) NOT NULL,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone NOT NULL
);


ALTER TABLE public.reservations OWNER TO postgres;

--
-- Name: reservations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reservations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: reservables; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reservables (id, name, type, isactive) FROM stdin;
4	プロジェクター	EQUIPMENT	t
16	test4	ROOM	t
47	GGGGGG	ROOM	t
56	テスト用会議室	ROOM	t
57	プロジェクター2号機	EQUIPMENT	t
\.


--
-- Data for Name: reservations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reservations (id, reservable_id, user_id, start_time, end_time) FROM stdin;
3	4	XXXX	2026-02-15 02:41:00	2026-02-15 03:41:00
7	4	XXXX	2026-02-18 09:00:00	2026-02-18 10:00:00
23	4	XXXX	2026-02-20 09:00:00	2026-02-20 10:00:00
24	56	XXXX	2026-02-20 09:00:00	2026-02-20 10:00:00
30	57	XXXX	2026-02-20 09:00:00	2026-02-20 10:00:00
\.


--
-- Name: reservables_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reservables_id_seq', 6, true);


--
-- Name: reservables_id_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reservables_id_seq1', 57, true);


--
-- Name: reservations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reservations_id_seq', 33, true);


--
-- Name: reservables reservables_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservables
    ADD CONSTRAINT reservables_pkey PRIMARY KEY (id);


--
-- Name: reservations reservations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT reservations_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict Hr2NXki0nOLDCZxAzfX5nF9YgSW2vVm3VL8gZw30mOcI0OWoVCQsRSkwctCeObc

